### ISSUE TITLE
Adding support for global actions

### ISSUE THREAD

**Issue by mkramb** [eloytoro/react-redux-uuid#3]
My use case is that all reusable components (common UI library) have the state which is isolated (with UUID). Majority of the actions are local, but some are generic and should be propagated to every reducer so that the app and other components can "react". This also assumes there is a convention how to define global actions ("global" prefix).

Is supporting global actions (for all reducers, not just uuid) something that you're thinking about supporting and if yes how would you go about doing that?

**Comment by eloytoro** [comment]
I believe this provides value to the project, however I'd like to see some practical examples to see if there's a better solution before merging #2
